---
- name: Create superset group.
  group:
    name: "{{ superset_group }}"

- name: Create superset user.
  user:
    name: "{{ superset_user }}"
    group: "{{ superset_group }}"
    shell: "{{ superset_shell }}"
    home: "{{ superset_home }}"
    create_home: yes

- name: Delete the Superset virtualenv directory
  file:
    state: absent
    path: "{{ superset_virtualenv_path }}"
  when: superset_recreate_virtualenv

- name: Make sure the Superset virtualenv directory exists
  file:
    state: directory
    path: "{{ superset_virtualenv_path }}"
    owner: "{{ superset_user }}"
    group: "{{ superset_group }}"
    recurse: yes

- name: Install Superset dependent pip libraries
  become: true
  become_user: "{{ superset_user }}"
  pip:
    name: "{{ superset_pip_dependencies_packages }}"
    state: latest
    virtualenv: "{{ superset_virtualenv_path }}"
    virtualenv_python: "{{ superset_python_executable }}"

- name: Install superset patchup (ketchup)
  become: true
  become_user: "{{ superset_user }}"
  pip:
    name: 'git+{{ superset_ketchup_git_url }}@{{ superset_ketchup_version }}'
    state: latest
    virtualenv: "{{ superset_virtualenv_path }}"
    virtualenv_python: "{{ superset_python_executable }}"
  when: superset_use_ketchup

- name: Install flask_cors
  become: true
  become_user: "{{ superset_user }}"
  pip:
    name: flask_cors
    state: latest
    virtualenv: "{{ superset_virtualenv_path }}"
    virtualenv_python: "{{ superset_python_executable }}"
  when: superset_enable_cors

- name: Install superset from pypi
  become: true
  become_user: "{{ superset_user }}"
  pip:
    name: "{{ superset_package_name }}"
    version: "{{ superset_version }}"
    virtualenv: "{{ superset_virtualenv_path }}"
    virtualenv_python: "{{ superset_python_executable }}"
  when: superset_install_from_git == False

- name: Install superset from git
  become: true
  become_user: "{{ superset_user }}"
  pip:
    name: 'git+{{ superset_git_url }}@{{ superset_version }}'
    state: latest
    virtualenv: "{{ superset_virtualenv_path }}"
    virtualenv_python: "{{ superset_python_executable }}"
  when: superset_install_from_git

- name: Install additional packages
  become: true
  become_user: "{{ superset_user }}"
  pip:
    name: "{{ superset_additional_pip_packages }}"
    virtualenv: "{{ superset_virtualenv_path }}"
    virtualenv_python: "{{ superset_python_executable }}"
  when: superset_install_additional_pip_packages

- name: Make sure the superset upload directories exists
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
    owner: "{{ superset_user }}"
    group: "{{ superset_group }}"
  with_items:
    - "{{ superset_img_upload_dir }}"
    - "{{ superset_upload_dir }}"
