---
- include: preinstall.yml
- include: postgres.yml
  when: superset_db_type == 'postgres'
  tags: database
- include: mysql.yml
  when: superset_db_type == 'mysql'
- include: install.yml
- include: config.yml
- include: white-label.yml
  when: superset_white_label == True
