- block:
  - name: Create postgres database
    postgresql_db:
      name: "{{ superset_db_name }}"
      login_host: "{{ superset_db_host }}"
      login_user: "{{ superset_db_login_user }}"
      login_password: "{{ superset_db_login_password }}"

  - name: Create postgres user
    postgresql_user:
      name: "{{ superset_db_user }}"
      password: "{{ superset_db_pass }}"
      encrypted: true
      db: "{{ superset_db_name }}"
      login_host: "{{ superset_db_host }}"
      login_user: "{{ superset_db_login_user }}"
      login_password: "{{ superset_db_login_password }}"
  when: superset_postgres_login == true

- block:
  - name: Create postgres database
    postgresql_db:
      name: "{{ superset_db_name }}"

  - name: Create postgres user
    postgresql_user:
      name: "{{ superset_db_user }}"
      password: "{{ superset_db_pass }}"
      encrypted: true
      db: "{{ superset_db_name }}"
  when: superset_postgres_login == false