- name: Gather variables for each operating system
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  tags:
    - always

- name: Add a Python 3.6 PPA
  apt_repository:
    repo: "ppa:jonathonf/python-3.6"
    state: present
  when: ansible_pkg_mgr == 'apt'

- name: install python
  package: 
    name: "{{ superset_python36_dependencies_packages }}"
  when: superset_python_executable == 'python3.6'

- name: install python
  package: 
    name: "{{ superset_python27_dependencies_packages }}"
  when: superset_python_executable == 'python2.7'

- name: install dependencies packages
  package: 
    name: "{{ superset_dependencies_packages }}"

- name: Install virtualenv via pip
  pip:
    name: "virtualenv"
    state: latest
    virtualenv_python: "{{ superset_python_executable }}"
    executable: pip